### ISSUE TITLE
Schwarmverhalten [Experiment]

### ISSUE THREAD

**Issue by DavidHieselmayr** [DavidHieselmayr/Gaias-resurrection#30]
## Experiment 

Schwarmverhalten wie bei Fischen. 

**Versuch**
- [x] Schwarmverhalten für Fische ermöglichen. 
- [x] Fischmodelle implementieren (30 Fische)
![external-content duckduckgo com](https://user-images.githubusercontent.com/43745537/102879185-b1ba2580-4449-11eb-852c-f7c827f69efc.jpg)

**Comment by FlorianBeckerle** [comment]
Something like this:
https://youtu.be/bqtqltqcQhw

**Comment by DavidHieselmayr** [comment]
wurde erfolgreich umgesetzt, bei Sprint #56 muss dieses Feature noch in die Hauptinsel implementiert werden.

derzeitige Testumgebung: Assets/Animals/Fauna/Boids/BoidTesting

**Comment by DavidHieselmayr** [comment]
derzeitige Idee: (Nahrungsbeschaffung Fisch) 

1. Angel (wenn der Schwarm gegen den Köder schwimmt, bekommt der Spieler einen Fisch, (Art des Fisches zufallsgeneriert)
2. Netz (es werden über die Zeit Fische generiert)
