### ISSUE TITLE
Inventarsystem 

### ISSUE THREAD

**Issue by DavidHieselmayr** [DavidHieselmayr/Gaias-resurrection#6]
- [x] Aufnahme von Gegenständen
- [x] Verschieben von Gegenständen 
- [x] Entfernen der verschiedenen Gegenstände möglich (Drop / Delete)

**Comment by DavidHieselmayr** [comment]
reopen: Inventar erweitert #13

**Comment by caberger** [comment]
Abgabe fehlt

**Comment by DavidHieselmayr** [comment]
#20

**Comment by DavidHieselmayr** [comment]
Die Fertigstellung ist nur gewährgeleistet, wenn der Sprint #27 abgeschlossen wurde
